In [1]:
import numpy as np

In [11]:
def plane_from_3_point(p1,p2,p3):
    p1 = np.array(p1)
    p2 = np.array(p2)
    p3 = np.array(p3)
    
    v1 = p2-p3
    v2 = p1-p3
    
    n = np.cross(v1,v2)
    
    return n, np.dot(n,p1)

In [13]:
plane_from_3_point([-1,-3,3], [2,0,6], [2,0,11])

(array([-15,  15,   0]), -30)

In [14]:
np.cross([-3,-5,-1],[0,0,1])

array([-5,  3,  0])

In [15]:
plane_from_3_point([1,6,1],[-3,7,-3],[5,1,1])

(array([ 20,  16, -16]), 100)

In [20]:
np.linalg.norm([20,16,-16])/2

15.0996688705415