In [1]:
import numpy as np

In [16]:
lst = [1, 2, 3] # A python list
arry1 = np.array(lst, dtype=float)

print(arry1)
print(arry1.shape) # (3,) means one dimensional array
print(arry1.dtype)

[1. 2. 3.]
(3,)
float64


In [17]:
type(arry)

numpy.ndarray

In [18]:
lst = [[1, 2, 3]] # A python list of lists
arry2 = np.array(lst, dtype=float)

print(arry2)
print(arry2.shape) # (1, 3): a 2D array with one row
print(arry2.dtype)

[[1. 2. 3.]]
(1, 3)
float64


## Functions to Create arrays
* empty(dims)
* zeros(dims)
* ones(dims)

In [25]:
# Create a 3x5 empty array. It is filled with random values.

arry = np.empty([3,5])
print(arry)

[[4.32887141e-311 5.02034658e+175 5.26418709e-037 3.37623417e-057
  2.19409595e-056]
 [5.53729051e+174 5.01163111e+217 5.49419094e-143 9.80058441e+252
  1.30304358e-142]
 [2.14027814e+161 9.28340494e+242 1.35617292e+248 8.66343214e-071
  5.54624426e+169]]


In [26]:
# Create a 3x5 array filled with 0's

arry = np.zeros([3,5])
print(arry)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
# Create a 3x5 array filled with 1's

arry = np.ones([3,5])
print(arry)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Combining Arrays
* vstack((arry1, arry2))
* hstack((arry1, arry2))

In [30]:
# Create two arrays with same dimensions

arry1 = np.array([1, 2, 3])
arry2 = np.array([4, 5, 6])

arry3 = np.vstack((arry1, arry2))
arry4 = np.hstack((arry1, arry2))

print(arry3,'\n')
print(arry4)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6]
