# Vectors and Vector Arithmetic

In [8]:
import numpy as np
from numpy import array

### Section 7.3: Defining a Vector

In [3]:
# define a vector
v = array([1, 2, 3])

print(v)
print(v.shape)

[1 2 3]
(3,)


### Section 7.4: Vector Arithmetic

In [7]:
a = array([2, -1, 7, 3])
b = array([3, 1, -5, 2])

# These operations work "element-wise"
c = a + b
d = a - b
e = a * b
f = a / b

print(f"{a} + {b} = {c}")
print(f"{a} - {b} = {d}")
print(f"{a} * {b} = {e}")
print(f"{a} / {b} = {f}"bb)

[ 2 -1  7  3] + [ 3  1 -5  2] = [5 0 2 5]
[ 2 -1  7  3] - [ 3  1 -5  2] = [-1 -2 12  1]
[ 2 -1  7  3] * [ 3  1 -5  2] = [  6  -1 -35   6]
[ 2 -1  7  3] / [ 3  1 -5  2] = [ 0.66666667 -1.         -1.4         1.5       ]


### Section 7.5: Vector Dot Product

In [10]:
a = np.random.randint(1,9,3)
b = np.random.randint(1,9,3)
a_dot_b = a.dot(b)

print(f"{a} . {b} = {a_dot_b}")

[3 3 3] . [4 8 8] = 60


### Section 7.6: Scalar Multiplication

In [12]:
a = np.random.randint(1,9,4)
k = -3

ka = k*a

print(f"{k} * {a} = {ka}")

-3 * [7 3 1 8] = [-21  -9  -3 -24]
