In [5]:
from numpy import exp, linspace, dot
import sympy as sy

In [2]:
def f(x):
    return 3*x**2 - 2

interval = np.arange(1, 4, 0.5)
print(interval)

[ 1.   1.5  2.   2.5  3.   3.5]


We imported "numpy" (a numerical python package) to have access to a lot of useful
methods (functions). In particular, I want the arange method which will create a
partition of an interval $[a, b]$ into equally spaced subintervals.

I defined a function $f(x) = 3x^2 - 2$. Notice the use of the double asterix for
exponentiation.

I used this method "arange" to create an interval which I called "interval". Note
that by default "arange" creates a partition of left endpoints of subintervals. One
of the nice things about these arrays of numbers is that we can apply functions to
them as a whole as the examples below illustrate.

In [3]:
print(interval + 0.5) # Add 0.5 to each element of the array

[ 1.5  2.   2.5  3.   3.5  4. ]


In [4]:
print(interval * 2) # Multiply each element of the array by 2

[ 2.  3.  4.  5.  6.  7.]


In [5]:
print(interval**2) # Square each element of the array

[  1.     2.25   4.     6.25   9.    12.25]


In [6]:
print(f(interval)) # Apply the function f to each element of the array

[  1.     4.75  10.    16.75  25.    34.75]


We can sum all the elements of an array with the "sum" function as shown below.

In [7]:
print(sum(f(interval))) # Riemann sum

92.25


In [1]:
# Evaluates the integral of func over the interval [a, b]
# using the a variety of formulas with n subintervals
from numpy import linspace, dot, exp
def numint(func, a, b, n, method="midptrule"):
    deltax = (b - a)/float(n)
    points = linspace(a, b, n+1)
    coeffs = []
    
    if method == "midptrule":
        midpts = [(points[i] + points[i+1])/2.0 for i in range(n)]
        return sum(map(func, midpts))*deltax
    
    elif method == "traprule":
        for k in xrange(n+1):
            if k == 0 or k == n:
                coeffs.append(1)
            else:
                coeffs.append(2)
                
        return deltax/2.0 * dot(coeffs, map(func,points))
    
    elif method == "simpsonrule":
        for k in xrange(n+1):
            if k == 0 or k == n:
                coeffs.append(1)
            elif k%2 == 1:
                coeffs.append(4)
            else:
                coeffs.append(2)
                                                
        return deltax/3.0 * dot(coeffs, map(func,points))
    
    else:
        print("Unsupported method")

In [2]:
def f(x):
    return exp(-x**2)

numint(f, -3, 3, 6, "simpsonrule")

1.8727632318012724

In [1]:
def simpson(f,a,b,n):
    xis = linspace(a, b, n+1)
    sum = 0.0
    for i in range(n+1):
        if i == 0 or i == n:
            sum = sum + f(xis[i])
        elif i % 2 == 1:
            sum = sum + 4*f(xis[i])
        else:
            sum = sum + 2*f(xis[i])
    return (b - a)/(3.0*n) * sum

In [21]:
def traprule(f,a,b,n):
    xis = linspace(a, b, n+1)
    sum = 0.0
    for i in range(n+1):
        if i == 0 or i == n:
            sum = sum + f(xis[i])
        else:
            sum = sum + 2*f(xis[i])
    return (b - a)/(2.0*n) * sum

In [23]:
print simpson(f, -3, 3, 6), numint(f, -3, 3, 6, "simpsonrule")
print traprule(f, -3, 3, 6), numint(f, -3, 3, 6, "traprule")

1.8727632318 1.8727632318
1.77251356992 1.77251356992


In [6]:
print simpson(f, -3, 3, 12)

1.772345139
