In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.35430421, -0.09831865, -0.85137373, -0.07373948, -1.66235892,
        0.43137321, -0.77692079, -0.13221512, -1.22991978,  0.95428356])

In [6]:
B = np.random.randn(10)
B

array([-2.14765457, -0.18636742,  0.6687189 ,  0.90144579,  0.55530595,
       -0.92191992, -0.48744188, -1.29539085,  1.63226466, -1.54258603])

In [7]:
#Binary Functions
np.add(A,B)

array([-1.79335036, -0.28468607, -0.18265484,  0.82770631, -1.10705298,
       -0.49054671, -1.26436267, -1.42760597,  0.40234488, -0.58830247])

In [8]:
np.maximum(A,B)

array([ 0.35430421, -0.09831865,  0.6687189 ,  0.90144579,  0.55530595,
        0.43137321, -0.48744188, -0.13221512,  1.63226466,  0.95428356])

In [9]:
np.minimum(A,B)

array([-2.14765457, -0.18636742, -0.85137373, -0.07373948, -1.66235892,
       -0.92191992, -0.77692079, -1.29539085, -1.22991978, -1.54258603])

In [10]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True